name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Chequea tu repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Instala Java (ajusta la versión si necesitas otra)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      # 3) Instala Gradle (por si no tienes wrapper en el repo)
      - name: Install Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      # 4) Ejecuta la compilación
      - name: Build with Gradle
        run: gradle build
